### ISSUE TITLE
Integration/Porting guide

### ISSUE THREAD

**Issue by taylor-bsg** [waviousllc/wav-lpddr-hw#10]
Very nice repo!

It would be super helpful to have an integration or porting guide that walks through the steps required to use this (i.e. which analog IP blocks need to be created) and/or to port this to a new node.

**Comment by pmclovis** [comment]
Thanks for the feedback. We will add some integration details to the documentation in the next release, which is currently TBD.

**Comment by pmclovis** [comment]
A "Technology" sub-section has been added to the "Integration" section that details which files need to be ported for a new process node.

Commit ID: 538e4d5635466edbb06dbac533e99b1174866411

**Comment by taylor-bsg** [comment]
Awesome, very cool!
