### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by olofk** [waviousllc/wav-lpddr-hw#9]
It's great to see that this has been made open source. It's unfortunate however to see that it has been done under the GPLv3 license. This license is exceptionally unfit for chip designs. [This video](https://www.youtube.com/watch?v=JgRBDuZQsFg) by Javier Serrano of CERN provides a detailed overview but in essence, the terms of GPLv3 basically prevents the use of designs using this license to be used in either ASIC or FPGA without violating the license. I'm not even sure it's permitted to create simulation models with proprietary simulators. A couple of suggestions for other licenses follows:

* Apache v2. This is the license to use if you are looking for commercial uptake. It's the preferred license by [CHIPS Alliance](https://chipsalliance.org/) and most larger companies I'm aware of

*  Solderpad. Very similar to Apache v2. Written with chip designs specifically in mind. Under stewardship of [FOSSi Foundation](https://fossi-foundation.org/) and preferred by [OpenHWGroup](https://www.openhwgroup.org/)

* If you are looking for the reciprocal aspects of the GPLv3 liense you would be much better off with the CERN-OHL-S verision of the [CERN OHL v2 family](https://ohwr.org/project/cernohl/wikis/Documents/CERN-OHL-version-2). This license was created to be similar in spirit to the GPLv3 but written specicifally with chip designs in mind

**Comment by pmclovis** [comment]
HW license has been updated to Apache2.0.

**Comment by mithro** [comment]
Awesome work!
